#!/usr/bin/env ruby

if ARGV.count < 1
  puts "USAGE: #$0 FILE"
  exit 1
end

require 'csv'
require_relative '../lib/literature_requests'
LR = LiteratureRequests

def person(cong, row)
  last, first = row[:lastfirst].split(/,\s*/)
  group_overseer_id = overseer_by_name(cong, row[:fsg_overseer]).id if cong
  LR::Person[last_name: last, first_name: first, email: row[:email], group_overseer_id: group_overseer_id, overseer: row[:overseer] || false]
end

def overseers(table)
  table
    .map { |r| r[:fsg_overseer] }
    .uniq
    .map { |name|
       table.find { |r| r[:lastfirst].split(/,\s*/).reverse.join(' ') == name } }
    .map { |r| person(nil, r.to_h.merge(overseer: true)) }
end

def overseer_by_name(cong, name)
  first, last = name.split(/\s+/)
  cong.find_by(first_name: first, last_name: last)
end

table = CSV.table(ARGV[0])
congregation = LR::Congregation.new
congregation.store_all!(overseers(table))

members = table.map do |row|
  person(congregation, row)
end

congregation.upsert_all!(members)
