#!/usr/bin/env ruby

if ARGV.count < 1
  puts "USAGE: #$0 FILE"
  exit 1
end

require 'csv'
require_relative '../lib/literature_requests'
LR = LiteratureRequests
PeopleStore = LR::People.new

def person(row)
  last, first = row[:lastfirst].split(/,\s*/)
  LR::Person[last_name: last, first_name: first, email: row[:email]]
end

def overseers(table)
  table
    .map { |r| r[:fsg_overseer] }
    .uniq
    .map { |name|
       table.find { |r| r[:lastfirst].split(/,\s*/).reverse.join(' ') == name } }
    .map { |r| person(r.merge(overseer: true)) }
end

def overseer_by_name(name)
  first, last = name.split(/\s+/)
  PeopleStore.find_by_name(first_name: first, last_name: last)
end

table = CSV.table(ARGV[0])
PeopleStore.store_all!(overseers(table))

#table.each do |row|
#  pp person(row)
#end
